# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kamran Payne
email: hello@kamranpayne.com
description: > # this means to ignore newlines until "baseurl:"
  This is the weblog and portfolio website of the programmer "arist" Kamran Payne.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kamranpayne.com" # the base hostname & protocol for your site
twitter_username: kamranpayne

# Build settings
markdown: kramdown
