


# Site settings
title: Kamran's Kracker Shack
email: hello@kamranpayne.com
description: "How did I get here?"
baseurl: "/"
url: "http://kamranpayne.com"
twitter_username: kamranpayne
github_username:  kmrn

# Build settings
markdown: kramdown
permalink: pretty

# Sass settings
sass:
    sass_dir: _sass

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      author: "Kamran Payne"
      category: "project"
