
gems:
- bourbon
- neat

markdown: kramdown

sass:
	style: :compressed

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      author: "Kamran Payne"
      category: "project"